name: pizzacorn_ui_example
description: "Demostración de los widgets de Pizzacorn UI"
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  pizzacorn_ui:
    path: ../  # Esto enlaza directamente con su librería local
  uicons_pro: ^1.1.0
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true