name: pizzacorn_ui
description: "Pizzacorn UI: a Flutter design system with configurable theme, typography, colors and reusable UI widgets."

version: 0.0.2

homepage: https://github.com/Pizzacorn/pizzacorn_ui
repository: https://github.com/Pizzacorn/pizzacorn_ui
issue_tracker: https://github.com/Pizzacorn/pizzacorn_ui/issues
topics:
  - widgets
  - ui
  - flutter

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
